/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ServiceCallsRouteImport } from './routes/service-calls'
import { Route as RestockRouteImport } from './routes/restock'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryAuditRouteImport } from './routes/inventory-audit'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CibusRouteImport } from './routes/cibus'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AidsRouteImport } from './routes/aids'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AidsIndexRouteImport } from './routes/aids.index'
import { Route as AidsSuppliersRouteImport } from './routes/aids.suppliers'
import { Route as AidsOperationsRouteImport } from './routes/aids.operations'
import { Route as AidsContactsRouteImport } from './routes/aids.contacts'
import { Route as AidsCleaningRouteImport } from './routes/aids.cleaning'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminSettingsEquipmentRouteImport } from './routes/admin.settings.equipment'
import { Route as ApiPublicHooksSportsSyncRouteImport } from './routes/api/public/hooks/sports-sync'
import { Route as ApiPublicHooksDoughAlertRouteImport } from './routes/api/public/hooks/dough-alert'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCallsRoute = ServiceCallsRouteImport.update({
  id: '/service-calls',
  path: '/service-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const RestockRoute = RestockRouteImport.update({
  id: '/restock',
  path: '/restock',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAuditRoute = InventoryAuditRouteImport.update({
  id: '/inventory-audit',
  path: '/inventory-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CibusRoute = CibusRouteImport.update({
  id: '/cibus',
  path: '/cibus',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AidsRoute = AidsRouteImport.update({
  id: '/aids',
  path: '/aids',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AidsIndexRoute = AidsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AidsRoute,
} as any)
const AidsSuppliersRoute = AidsSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AidsRoute,
} as any)
const AidsOperationsRoute = AidsOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AidsRoute,
} as any)
const AidsContactsRoute = AidsContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AidsRoute,
} as any)
const AidsCleaningRoute = AidsCleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => AidsRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsEquipmentRoute = AdminSettingsEquipmentRouteImport.update({
  id: '/settings/equipment',
  path: '/settings/equipment',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksSportsSyncRoute =
  ApiPublicHooksSportsSyncRouteImport.update({
    id: '/api/public/hooks/sports-sync',
    path: '/api/public/hooks/sports-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDoughAlertRoute =
  ApiPublicHooksDoughAlertRouteImport.update({
    id: '/api/public/hooks/dough-alert',
    path: '/api/public/hooks/dough-alert',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aids': typeof AidsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/cibus': typeof CibusRoute
  '/complaints': typeof ComplaintsRoute
  '/guide': typeof GuideRoute
  '/inventory-audit': typeof InventoryAuditRoute
  '/invoices': typeof InvoicesRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-profile': typeof MyProfileRoute
  '/notebook': typeof NotebookRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/prep': typeof PrepRoute
  '/recipes': typeof RecipesRoute
  '/restock': typeof RestockRoute
  '/service-calls': typeof ServiceCallsRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/aids/cleaning': typeof AidsCleaningRoute
  '/aids/contacts': typeof AidsContactsRoute
  '/aids/operations': typeof AidsOperationsRoute
  '/aids/suppliers': typeof AidsSuppliersRoute
  '/aids/': typeof AidsIndexRoute
  '/admin/settings/equipment': typeof AdminSettingsEquipmentRoute
  '/api/public/hooks/dough-alert': typeof ApiPublicHooksDoughAlertRoute
  '/api/public/hooks/sports-sync': typeof ApiPublicHooksSportsSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/cibus': typeof CibusRoute
  '/complaints': typeof ComplaintsRoute
  '/guide': typeof GuideRoute
  '/inventory-audit': typeof InventoryAuditRoute
  '/invoices': typeof InvoicesRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-profile': typeof MyProfileRoute
  '/notebook': typeof NotebookRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/prep': typeof PrepRoute
  '/recipes': typeof RecipesRoute
  '/restock': typeof RestockRoute
  '/service-calls': typeof ServiceCallsRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/aids/cleaning': typeof AidsCleaningRoute
  '/aids/contacts': typeof AidsContactsRoute
  '/aids/operations': typeof AidsOperationsRoute
  '/aids/suppliers': typeof AidsSuppliersRoute
  '/aids': typeof AidsIndexRoute
  '/admin/settings/equipment': typeof AdminSettingsEquipmentRoute
  '/api/public/hooks/dough-alert': typeof ApiPublicHooksDoughAlertRoute
  '/api/public/hooks/sports-sync': typeof ApiPublicHooksSportsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aids': typeof AidsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/cibus': typeof CibusRoute
  '/complaints': typeof ComplaintsRoute
  '/guide': typeof GuideRoute
  '/inventory-audit': typeof InventoryAuditRoute
  '/invoices': typeof InvoicesRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-profile': typeof MyProfileRoute
  '/notebook': typeof NotebookRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/prep': typeof PrepRoute
  '/recipes': typeof RecipesRoute
  '/restock': typeof RestockRoute
  '/service-calls': typeof ServiceCallsRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/aids/cleaning': typeof AidsCleaningRoute
  '/aids/contacts': typeof AidsContactsRoute
  '/aids/operations': typeof AidsOperationsRoute
  '/aids/suppliers': typeof AidsSuppliersRoute
  '/aids/': typeof AidsIndexRoute
  '/admin/settings/equipment': typeof AdminSettingsEquipmentRoute
  '/api/public/hooks/dough-alert': typeof ApiPublicHooksDoughAlertRoute
  '/api/public/hooks/sports-sync': typeof ApiPublicHooksSportsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aids'
    | '/calendar'
    | '/cibus'
    | '/complaints'
    | '/guide'
    | '/inventory-audit'
    | '/invoices'
    | '/maintenance'
    | '/my-profile'
    | '/notebook'
    | '/notifications'
    | '/orders'
    | '/prep'
    | '/recipes'
    | '/restock'
    | '/service-calls'
    | '/suppliers'
    | '/tasks'
    | '/admin/alerts'
    | '/admin/history'
    | '/aids/cleaning'
    | '/aids/contacts'
    | '/aids/operations'
    | '/aids/suppliers'
    | '/aids/'
    | '/admin/settings/equipment'
    | '/api/public/hooks/dough-alert'
    | '/api/public/hooks/sports-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/cibus'
    | '/complaints'
    | '/guide'
    | '/inventory-audit'
    | '/invoices'
    | '/maintenance'
    | '/my-profile'
    | '/notebook'
    | '/notifications'
    | '/orders'
    | '/prep'
    | '/recipes'
    | '/restock'
    | '/service-calls'
    | '/suppliers'
    | '/tasks'
    | '/admin/alerts'
    | '/admin/history'
    | '/aids/cleaning'
    | '/aids/contacts'
    | '/aids/operations'
    | '/aids/suppliers'
    | '/aids'
    | '/admin/settings/equipment'
    | '/api/public/hooks/dough-alert'
    | '/api/public/hooks/sports-sync'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aids'
    | '/calendar'
    | '/cibus'
    | '/complaints'
    | '/guide'
    | '/inventory-audit'
    | '/invoices'
    | '/maintenance'
    | '/my-profile'
    | '/notebook'
    | '/notifications'
    | '/orders'
    | '/prep'
    | '/recipes'
    | '/restock'
    | '/service-calls'
    | '/suppliers'
    | '/tasks'
    | '/admin/alerts'
    | '/admin/history'
    | '/aids/cleaning'
    | '/aids/contacts'
    | '/aids/operations'
    | '/aids/suppliers'
    | '/aids/'
    | '/admin/settings/equipment'
    | '/api/public/hooks/dough-alert'
    | '/api/public/hooks/sports-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AidsRoute: typeof AidsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CibusRoute: typeof CibusRoute
  ComplaintsRoute: typeof ComplaintsRoute
  GuideRoute: typeof GuideRoute
  InventoryAuditRoute: typeof InventoryAuditRoute
  InvoicesRoute: typeof InvoicesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MyProfileRoute: typeof MyProfileRoute
  NotebookRoute: typeof NotebookRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PrepRoute: typeof PrepRoute
  RecipesRoute: typeof RecipesRoute
  RestockRoute: typeof RestockRoute
  ServiceCallsRoute: typeof ServiceCallsRoute
  SuppliersRoute: typeof SuppliersRoute
  TasksRoute: typeof TasksRoute
  ApiPublicHooksDoughAlertRoute: typeof ApiPublicHooksDoughAlertRoute
  ApiPublicHooksSportsSyncRoute: typeof ApiPublicHooksSportsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-calls': {
      id: '/service-calls'
      path: '/service-calls'
      fullPath: '/service-calls'
      preLoaderRoute: typeof ServiceCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restock': {
      id: '/restock'
      path: '/restock'
      fullPath: '/restock'
      preLoaderRoute: typeof RestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-audit': {
      id: '/inventory-audit'
      path: '/inventory-audit'
      fullPath: '/inventory-audit'
      preLoaderRoute: typeof InventoryAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cibus': {
      id: '/cibus'
      path: '/cibus'
      fullPath: '/cibus'
      preLoaderRoute: typeof CibusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aids': {
      id: '/aids'
      path: '/aids'
      fullPath: '/aids'
      preLoaderRoute: typeof AidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aids/': {
      id: '/aids/'
      path: '/'
      fullPath: '/aids/'
      preLoaderRoute: typeof AidsIndexRouteImport
      parentRoute: typeof AidsRoute
    }
    '/aids/suppliers': {
      id: '/aids/suppliers'
      path: '/suppliers'
      fullPath: '/aids/suppliers'
      preLoaderRoute: typeof AidsSuppliersRouteImport
      parentRoute: typeof AidsRoute
    }
    '/aids/operations': {
      id: '/aids/operations'
      path: '/operations'
      fullPath: '/aids/operations'
      preLoaderRoute: typeof AidsOperationsRouteImport
      parentRoute: typeof AidsRoute
    }
    '/aids/contacts': {
      id: '/aids/contacts'
      path: '/contacts'
      fullPath: '/aids/contacts'
      preLoaderRoute: typeof AidsContactsRouteImport
      parentRoute: typeof AidsRoute
    }
    '/aids/cleaning': {
      id: '/aids/cleaning'
      path: '/cleaning'
      fullPath: '/aids/cleaning'
      preLoaderRoute: typeof AidsCleaningRouteImport
      parentRoute: typeof AidsRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/equipment': {
      id: '/admin/settings/equipment'
      path: '/settings/equipment'
      fullPath: '/admin/settings/equipment'
      preLoaderRoute: typeof AdminSettingsEquipmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/sports-sync': {
      id: '/api/public/hooks/sports-sync'
      path: '/api/public/hooks/sports-sync'
      fullPath: '/api/public/hooks/sports-sync'
      preLoaderRoute: typeof ApiPublicHooksSportsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dough-alert': {
      id: '/api/public/hooks/dough-alert'
      path: '/api/public/hooks/dough-alert'
      fullPath: '/api/public/hooks/dough-alert'
      preLoaderRoute: typeof ApiPublicHooksDoughAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminSettingsEquipmentRoute: typeof AdminSettingsEquipmentRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminSettingsEquipmentRoute: AdminSettingsEquipmentRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AidsRouteChildren {
  AidsCleaningRoute: typeof AidsCleaningRoute
  AidsContactsRoute: typeof AidsContactsRoute
  AidsOperationsRoute: typeof AidsOperationsRoute
  AidsSuppliersRoute: typeof AidsSuppliersRoute
  AidsIndexRoute: typeof AidsIndexRoute
}

const AidsRouteChildren: AidsRouteChildren = {
  AidsCleaningRoute: AidsCleaningRoute,
  AidsContactsRoute: AidsContactsRoute,
  AidsOperationsRoute: AidsOperationsRoute,
  AidsSuppliersRoute: AidsSuppliersRoute,
  AidsIndexRoute: AidsIndexRoute,
}

const AidsRouteWithChildren = AidsRoute._addFileChildren(AidsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AidsRoute: AidsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CibusRoute: CibusRoute,
  ComplaintsRoute: ComplaintsRoute,
  GuideRoute: GuideRoute,
  InventoryAuditRoute: InventoryAuditRoute,
  InvoicesRoute: InvoicesRoute,
  MaintenanceRoute: MaintenanceRoute,
  MyProfileRoute: MyProfileRoute,
  NotebookRoute: NotebookRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PrepRoute: PrepRoute,
  RecipesRoute: RecipesRoute,
  RestockRoute: RestockRoute,
  ServiceCallsRoute: ServiceCallsRoute,
  SuppliersRoute: SuppliersRoute,
  TasksRoute: TasksRoute,
  ApiPublicHooksDoughAlertRoute: ApiPublicHooksDoughAlertRoute,
  ApiPublicHooksSportsSyncRoute: ApiPublicHooksSportsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
