/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as RestockRouteImport } from './routes/restock'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminSettingsEquipmentRouteImport } from './routes/admin.settings.equipment'
import { Route as ApiPublicHooksSportsSyncRouteImport } from './routes/api/public/hooks/sports-sync'
import { Route as ApiPublicHooksDoughAlertRouteImport } from './routes/api/public/hooks/dough-alert'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const RestockRoute = RestockRouteImport.update({
  id: '/restock',
  path: '/restock',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsEquipmentRoute = AdminSettingsEquipmentRouteImport.update({
  id: '/settings/equipment',
  path: '/settings/equipment',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksSportsSyncRoute =
  ApiPublicHooksSportsSyncRouteImport.update({
    id: '/api/public/hooks/sports-sync',
    path: '/api/public/hooks/sports-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDoughAlertRoute =
  ApiPublicHooksDoughAlertRouteImport.update({
    id: '/api/public/hooks/dough-alert',
    path: '/api/public/hooks/dough-alert',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/guide': typeof GuideRoute
  '/invoices': typeof InvoicesRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-profile': typeof MyProfileRoute
  '/notebook': typeof NotebookRoute
  '/orders': typeof OrdersRoute
  '/prep': typeof PrepRoute
  '/recipes': typeof RecipesRoute
  '/restock': typeof RestockRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/settings/equipment': typeof AdminSettingsEquipmentRoute
  '/api/public/hooks/dough-alert': typeof ApiPublicHooksDoughAlertRoute
  '/api/public/hooks/sports-sync': typeof ApiPublicHooksSportsSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/guide': typeof GuideRoute
  '/invoices': typeof InvoicesRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-profile': typeof MyProfileRoute
  '/notebook': typeof NotebookRoute
  '/orders': typeof OrdersRoute
  '/prep': typeof PrepRoute
  '/recipes': typeof RecipesRoute
  '/restock': typeof RestockRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/settings/equipment': typeof AdminSettingsEquipmentRoute
  '/api/public/hooks/dough-alert': typeof ApiPublicHooksDoughAlertRoute
  '/api/public/hooks/sports-sync': typeof ApiPublicHooksSportsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/guide': typeof GuideRoute
  '/invoices': typeof InvoicesRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-profile': typeof MyProfileRoute
  '/notebook': typeof NotebookRoute
  '/orders': typeof OrdersRoute
  '/prep': typeof PrepRoute
  '/recipes': typeof RecipesRoute
  '/restock': typeof RestockRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/settings/equipment': typeof AdminSettingsEquipmentRoute
  '/api/public/hooks/dough-alert': typeof ApiPublicHooksDoughAlertRoute
  '/api/public/hooks/sports-sync': typeof ApiPublicHooksSportsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/guide'
    | '/invoices'
    | '/maintenance'
    | '/my-profile'
    | '/notebook'
    | '/orders'
    | '/prep'
    | '/recipes'
    | '/restock'
    | '/suppliers'
    | '/tasks'
    | '/admin/alerts'
    | '/admin/history'
    | '/admin/maintenance'
    | '/admin/settings/equipment'
    | '/api/public/hooks/dough-alert'
    | '/api/public/hooks/sports-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/guide'
    | '/invoices'
    | '/maintenance'
    | '/my-profile'
    | '/notebook'
    | '/orders'
    | '/prep'
    | '/recipes'
    | '/restock'
    | '/suppliers'
    | '/tasks'
    | '/admin/alerts'
    | '/admin/history'
    | '/admin/maintenance'
    | '/admin/settings/equipment'
    | '/api/public/hooks/dough-alert'
    | '/api/public/hooks/sports-sync'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/guide'
    | '/invoices'
    | '/maintenance'
    | '/my-profile'
    | '/notebook'
    | '/orders'
    | '/prep'
    | '/recipes'
    | '/restock'
    | '/suppliers'
    | '/tasks'
    | '/admin/alerts'
    | '/admin/history'
    | '/admin/maintenance'
    | '/admin/settings/equipment'
    | '/api/public/hooks/dough-alert'
    | '/api/public/hooks/sports-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  GuideRoute: typeof GuideRoute
  InvoicesRoute: typeof InvoicesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MyProfileRoute: typeof MyProfileRoute
  NotebookRoute: typeof NotebookRoute
  OrdersRoute: typeof OrdersRoute
  PrepRoute: typeof PrepRoute
  RecipesRoute: typeof RecipesRoute
  RestockRoute: typeof RestockRoute
  SuppliersRoute: typeof SuppliersRoute
  TasksRoute: typeof TasksRoute
  ApiPublicHooksDoughAlertRoute: typeof ApiPublicHooksDoughAlertRoute
  ApiPublicHooksSportsSyncRoute: typeof ApiPublicHooksSportsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restock': {
      id: '/restock'
      path: '/restock'
      fullPath: '/restock'
      preLoaderRoute: typeof RestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/equipment': {
      id: '/admin/settings/equipment'
      path: '/settings/equipment'
      fullPath: '/admin/settings/equipment'
      preLoaderRoute: typeof AdminSettingsEquipmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/sports-sync': {
      id: '/api/public/hooks/sports-sync'
      path: '/api/public/hooks/sports-sync'
      fullPath: '/api/public/hooks/sports-sync'
      preLoaderRoute: typeof ApiPublicHooksSportsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dough-alert': {
      id: '/api/public/hooks/dough-alert'
      path: '/api/public/hooks/dough-alert'
      fullPath: '/api/public/hooks/dough-alert'
      preLoaderRoute: typeof ApiPublicHooksDoughAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminSettingsEquipmentRoute: typeof AdminSettingsEquipmentRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminSettingsEquipmentRoute: AdminSettingsEquipmentRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarRoute: CalendarRoute,
  GuideRoute: GuideRoute,
  InvoicesRoute: InvoicesRoute,
  MaintenanceRoute: MaintenanceRoute,
  MyProfileRoute: MyProfileRoute,
  NotebookRoute: NotebookRoute,
  OrdersRoute: OrdersRoute,
  PrepRoute: PrepRoute,
  RecipesRoute: RecipesRoute,
  RestockRoute: RestockRoute,
  SuppliersRoute: SuppliersRoute,
  TasksRoute: TasksRoute,
  ApiPublicHooksDoughAlertRoute: ApiPublicHooksDoughAlertRoute,
  ApiPublicHooksSportsSyncRoute: ApiPublicHooksSportsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
